# Build the module and save it locally
# We're saving the artifacts that are then used later on to execute the tests
# The artifacts are also stored and made available through circleci UI if further investigations are necessary
description: >
  Build a Java codebase with maven

parameters:
  resource_class:
    type: string
    default: "large"
    description: "CircleCI resource_class (small, medium, large, xlarge, ...)"
  working_directory:
    type: string
    default: "~/source"
    description: "Working directory for the job"
  base_image:
    type: string
    default: "jahia/cimg-mvn-cache:cimg_openjdk_8.0.275"
    description: "Base docker image to be used for running the job"
  module_id:
    type: string
    default: "module_id"
    description: "ID of the module being built. This is only useful when the module built is part of a package."

working_directory: << parameters.working_directory >>

resource_class: << parameters.resource_class >>

docker:
  - image: << parameters.base_image >>

steps:
  - attach_workspace:
      at: .
  - run:
      name: Display size of the workspace folders before running job (for space optimization)
      command: du -h -d 1 << parameters.working_directory >>
  - run:
      name: Build package
      command: mvn -s .circleci/.circleci.settings.xml clean install
  - run:
      name: Copy dependencies to provision artifacts
      command: mvn -ntp -s .circleci/.circleci.settings.xml dependency:copy-dependencies -DexcludeTransitive=true -DincludeScope=provided -DincludeGroupIds=org.jahia.modules -DincludeTypes=jar
  - run:
      name: Prepare artifacts
      command: |
        mkdir /tmp/artifacts/
        find . -type f -path '*/target/*-SNAPSHOT*.jar' -exec cp '{}' /tmp/artifacts/ ';' || :
        if [ -f /home/circleci/source/target/*source-release.zip ]; then
          echo "A source file is present, copying it to the artifacts folder"
          cp /home/circleci/source/target/*source-release.zip /tmp/artifacts/ || :
        fi
        if [ -d /home/circleci/source/<< parameters.module_id >>/ ]; then
          echo "Copying jar from: /home/circleci/source/<< parameters.module_id >>/"
          cp /home/circleci/source/<< parameters.module_id >>/target/*.jar /tmp/artifacts/ || :
          if [ ! -d /home/circleci/source/target/ ]; then
            mkdir /home/circleci/source/target/
          fi
          cp /home/circleci/source/<< parameters.module_id >>/target/*.jar /home/circleci/source/target/ || :
        fi
  # Note: The two steps below are derived from graphql-dxm-provider setup
  # This might not be applicable to other modules for the same complexity
  - run:
      name: Copy test report (if present)
      command: |
        mkdir /tmp/artifacts/test-results/
        if [ -d /home/circleci/source/<< parameters.module_id >>/target/surefire-reports/ ]; then
          cp /home/circleci/source/graphql-dxm-provider/target/surefire-reports/*.xml /tmp/artifacts/test-results/ || :
        fi
  - run:
      name: Copy test report details (if present)
      command: |
        if [ -d /home/circleci/source/<< parameters.module_id >>/target/surefire-reports/ ]; then
          echo "Folder exists: /home/circleci/source/<< parameters.module_id >>/target/surefire-reports/"
          mkdir /tmp/artifacts/surefire-reports/
          cp /home/circleci/source/<< parameters.module_id >>/target/surefire-reports/*.txt /tmp/artifacts/surefire-reports/ || :
        fi
        if [ -d /home/circleci/source/<< parameters.module_id >>/target/surefire-reports/testng-junit-results/ ]; then
          echo "Folder exists: /home/circleci/source/<< parameters.module_id >>/target/surefire-reports/testng-junit-results/"
          mkdir /tmp/artifacts/surefire-reports/testng-junit-results/
          cp /home/circleci/source/<< parameters.module_id >>/target/surefire-reports/testng-junit-results/* /tmp/artifacts/surefire-reports/testng-junit-results/ || :
        fi
        if [ -d /home/circleci/source/<< parameters.module_id >>/target/surefire-reports/testng-junit-results/junitreports/ ]; then
          echo "Folder exists: /home/circleci/source/<< parameters.module_id >>/target/surefire-reports/testng-junit-results/junitreports/"
          mkdir /tmp/artifacts/surefire-reports/testng-junit-results/junitreports/
          cp /home/circleci/source/graphql-dxm-provider/target/surefire-reports/testng-junit-results/junitreports/* /tmp/artifacts/surefire-reports/testng-junit-results/junitreports/ || :
        fi
  - store_artifacts:
      path: /tmp/artifacts/
  - store_test_results:
      path: /tmp/artifacts/test-results/
  - run:
      name: Display size of the workspace folders after running job (for space optimization)
      command: du -h -d 1 << parameters.working_directory >>
  - persist_to_workspace:
      root: << parameters.working_directory >>
      paths:
        - target/*
